name: Validation

on:
    pull_request:

    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/validation.yml"
            - "dnsconfig.js"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-validation
    cancel-in-progress: true

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Check
              uses: is-cool-me/dnscontrol-action@v4.11.0
              with:
                  args: check
                  config_file: "dnsconfig.js"

    json:
        name: JSON
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: JSON Syntax Check
              uses: limitusus/json-syntax-check@v2
              with:
                  pattern: "\\.json$"
              env:
                  BASE: "domains/"

    pr:
      runs-on: ubuntu-latest
      steps:
            - name: Save PR number
              env:
                PR_NUMBER: ${{ github.event.number }}
              run: |
                mkdir -p ./pr
                echo $PR_NUMBER > ./pr/pr_number
            - uses: actions/upload-artifact@v4
              with:
                name: pr_number
                path: pr/
